#!/bin/bash

# set -e

ROOT_DIR=$1
PROJECT_LAYOUT=$2
NAMING_STANDARD=""

############################################################
### Error exit function
############################################################
callback_validation()
{
    if [ -z "${1}" ];
    then
        echo "[OK]"
    else
        echo "[FAIL]"
        printf "${1:-}\n"
        exit -1
    fi
}

############################################################
### Checking the directory structure using a layout 
### generated by tree
############################################################
echo -n "Checking directory layout ... "
CHECKDIR=$(python /usr/bin/layoutcheck.py <(curl -s ${PROJECT_LAYOUT}) <(find . -maxdepth 2 -type d | grep -v .git |sort))
callback_validation "$CHECKDIR"
    
############################################################
### Checking for file and directory names to be in the  
### correct standard
############################################################
echo -n "Checking filename standards ... "
CHECKNAMES=$(find . -not -path './.git/*' | grep '[^a-z\._/0-9]' | grep -i -v -E "README|MANIFEST|Snakefile|Makefile|LICENSE|Snakejob" )
callback_validation "${CHECKNAMES}"