#!/bin/bash

set -e

ROOT_DIR=$1
PROJECT_LAYOUT=$2
NAMING_STANDARD=""

############################################################
### Checking the directory structure using a layout 
### generated by tree
############################################################
echo "Checking directory layout ... "
python3 /usr/bin/layoutcheck.py <(curl -s ${PROJECT_LAYOUT}) <(find . -maxdepth 2 -type d | grep -v .git |sort)
echo "...OK"    
############################################################
### Checking for file and directory names to be in the  
### correct standard
############################################################
echo "Checking filename standards ... "
python3 /usr/bin/namecheck.py . ./.git,./data/raw,./data/external Snakefile,Snakejob,README,LICENSE
echo "...OK"